#!/usr/bin/env python3
"""DELIVERABLE CHECK — measure twice, cut once.

Three fix-audit cycles on one deliverable produced roughly as many new defects as
they closed. Every one of the new defects had the same cause: **two artifacts,
generated by two mechanisms, patched independently.** A fix landed in the workbook
and not the markdown, or the reverse, and the disagreement shipped.

Reviewing afterwards does not fix that. Review is a cut followed by a measurement.
This runs BEFORE the artifacts are allowed to ship, and it FAILS THE BUILD — so the
measuring happens twice and the cutting happens once.

Checks, each one derived from a defect that actually shipped:

  C1  md and xlsx must agree on every shared number.        (5 disclosures once
      lived only in the workbook; the markdown is the file that gets forwarded)
  C2  no value from a _SUPERSEDED block may appear.         (retracted ceilings)
  C3  no "not measured" claim may name something that IS.   (both files said the
      IQ-9075 fp16 was never measured, on the page containing it)
  C4  a blacklist of phrases known to be wrong.             (they came back twice)
  C5  every number in the deliverable must exist in source. (catches hardcoding,
      which is what let the two files drift apart)
  C6  claimed replicate counts must match the source.       ("median of 3" where
      the source holds 2)

Exit non-zero on any failure. Wire into the builder, not into a review checklist.
"""
import json
import os
import re
import sys

# --- A/B instrumentation (campaign_log) -------------------------------------
# Automatic on purpose: the hardest lesson of this project is that a rule enforced
# by remembering is enforced sometimes. The checker logs its own trips.
try:
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from campaign_log import log_event as _log_event
except Exception:
    def _log_event(*a, **k):
        pass

HERE = os.path.dirname(os.path.abspath(__file__))
BENCH = os.path.dirname(HERE)
RESULTS = os.path.dirname(BENCH)
SRC = os.path.join(BENCH, "remeasure", "colleague_yolo_llama_2026-08-14.json")

# Phrases that shipped, were corrected, and must never return.
BLACKLIST = [
    ("no asterisk needed", "a 1.9% margin over an unreplicated older-vintage engine, "
                           "against an accuracy comparator this dataset calls a FLOOR"),
    ("never measured", "check it against what IS in the source before claiming absence"),
    ("only int8 was measured", "the IQ-9075 fp16 tier exists"),
    ("quoted at its own best", "Thor's YOLOv8L is faster at 120W than at the quoted MAXN"),
    ("median of three independent builds", "the quoted values are single builds"),
    ("close to Thor", "they are 2.59x apart"),
    ("OCRAM", "our gloss, not a vendor term"),
    ("25.5%", "withdrawn noise floor - only the sentence retracting it may mention it"),
]
BLACKLIST_ALLOW = ["was inferred rather than measured and is withdrawn"]


def walk(o, path=""):
    if isinstance(o, dict):
        for k, v in o.items():
            yield from walk(v, f"{path}.{k}" if path else k)
    elif isinstance(o, list):
        for i, v in enumerate(o):
            yield from walk(v, f"{path}[{i}]")
    else:
        yield path, o


def numbers_in(text):
    """Decimal numbers that look like measurements, not years/counts/percent-signs."""
    out = set()
    # The lookahead excluded a following DIGIT but not a following LETTER, so a number
    # embedded in a hex token was harvested as data: "52fdb131daa7" (an engine md5) yielded
    # 52, which then failed the md-vs-xlsx agreement check. Any document quoting a hash
    # would trip this. Exclude a following word character too.
    # Strip comma-grouped numbers and identifier-embedded digits BEFORE extraction.
    #   "5,129,336,956 B"  yielded 5 / 129 / 336 / 956 -- four numbers that never existed.
    #   "IQ-9075"          yielded 9075, a part number in a NAME.
    #   "Adreno 663"       yielded 663, a product name.
    # None of these are measurements, and each generated a warning that a reader would have
    # to dismiss by hand -- which is how a warning list becomes noise and stops being read.
    # A MULTIPLIER SUFFIX MUST NOT CHANGE WHETHER A NUMBER IS SEEN. The workbook renders
    # "6.1x" (ASCII x, a word char, which the lookahead below blocks) while the markdown
    # renders "6.1x" with the multiplication sign (not a word char, so it extracts). The
    # SAME claim therefore looked md-only and reported as one-sided drift four times.
    # Detach the suffix first so both spellings parse identically.
    text = re.sub(r"(\d)\s*[x\u00d7](?![\w])", r"\1 ", text)
    text = re.sub(r"\b\d{1,3}(?:,\d{3})+\b", " ", text)          # comma-grouped magnitudes
    text = re.sub(r"\b[A-Za-z]+-?\d+\b", " ", text)              # IQ-9075, T234, sm_110
    # Product names only, and only when the digits are NOT the start of a decimal. Including
    # Orin/Thor here was wrong: they are board names routinely followed by a measurement, so
    # "Orin 0.26%" was stripped as if it were a product number and the floor vanished from
    # the md side of the comparison. A filter that removes real data is worse than the noise
    # it was written to remove.
    text = re.sub(r"\b(?:Adreno|Kryo|Tegra)\s+\d+(?!\.\d)\b", " ", text)  # product names
    # The lookahead blocked ANY following period, so a number ending a sentence -- "IQ-9075
    # 6.3." -- was never extracted, and the same value written mid-sentence elsewhere then
    # looked like one-sided drift. Block a following word char, and block ".<digit>" (a
    # decimal continuation), but allow a bare sentence-ending period.
    for m in re.finditer(r"(?<![\w.])(\d+(?:\.\d+)?)(?!\w|\.\d)", text):
        v = float(m.group(1))
        if v.is_integer() and (1900 <= v <= 2100 or v <= 20):
            continue          # years, section numbers, small counts
        if 0.001 < abs(v) < 1e6:
            out.add(round(v, 4))
    return out


def load_xlsx_text(path):
    try:
        import openpyxl
    except ImportError:
        return None
    wb = openpyxl.load_workbook(path)
    return "\n".join(str(c.value) for ws in wb for row in ws.iter_rows()
                     for c in row if c.value is not None)



# ─────────────────────────────────────────────────────────────────────────────
def self_test():
    """NEGATIVE CONTROL. This file had none, which is why an adversarial agent -- not the
    tool -- discovered that 6 of 7 planted defects passed. A checker that has never been
    shown a defect it must catch is an assertion, not an instrument.

    Every case below is a defect this corpus actually produced."""
    import io, contextlib
    SRC_N = {7.234, 1.699, 2.1765, 8.9844, 450.0, 0.4192}
    PROSE = {53.81, 1.68}

    def c5(n):
        """The C5 decision for one deliverable number, given the pools above."""
        if n in SRC_N:
            return "pass"
        d = len(str(n).split('.')[-1]) if '.' in str(n) else 0
        if any(abs(n - s) <= 0.5 * (10 ** -d) + 1e-12 for s in SRC_N):
            return "pass"
        if any(abs(n - s / q) < 0.002 for s in SRC_N for q in (2, 3, 4, 8, 16)):
            return "pass"
        if any(abs(n - s * q) < 0.002 for s in SRC_N for q in (2, 3, 4)):
            return "pass"
        is_meas = (round(n, 4) != round(n, 1)) or (n != int(n) and d >= 2)
        if not is_meas:
            return "warn"
        return "prose" if round(n, 4) in PROSE else "fail"

    cases = [
        # (name, value, expected)
        ("a value straight from the source",                     7.234,  "pass"),
        ("THE ROUNDING-MODE TRAP: 2.1765 shown half-up as 2.177 "
         "(Python round() gives 2.176 and called it untraceable)", 2.177, "pass"),
        ("a per-image derivation of a source value",             2.2461, "pass"),
        ("THE FABRICATION: measurement-shaped, in no pool",       9.812,  "fail"),
        ("a fabricated value one digit off a real one",           7.334,  "fail"),
        ("PROSE-ONLY: real, but narrated with no field/unit",    53.81,  "prose"),
        ("PROSE-ONLY perf/W ratio",                               1.68,   "prose"),
        ("an integer that is probably config, not a measurement", 450.0,  "pass"),
    ]
    bad = 0
    for name, val, want in cases:
        got = c5(val)
        ok = got == want
        bad += (not ok)
        print(f"  [{'ok ' if ok else 'BUG'}] {str(val):<8} got={got:<5} want={want:<5} {name}")

    # C5 must BLOCK, not warn. This is the defect that made the whole tool decorative:
    # its stated job is "catches hardcoding" and it appended to warns, so the corpus
    # reported 0 failures / 235 warnings while holding 49 typed decimals.
    src = open(__file__).read()
    blocks = 'fails.append(\n                        f"C5' in src or 'fails.append(' in src.split('C5 BLOCKS')[1][:400]
    print(f"  [{'ok ' if blocks else 'BUG'}] C5 appends to fails (blocking), not warns")
    bad += (not blocks)

    print(f"\n{len(cases)+1-bad}/{len(cases)+1} self-test cases pass")
    _log_event("gate_pass" if not bad else "gate_trip", tool="deliverable_check",
               check="SELF_TEST", n_fail=bad)
    return 1 if bad else 0


def main():
    md_path = os.path.join(RESULTS, "IQ9075_vs_OrinAGX_vs_Thor_Colleague_Request.md")
    xl_path = os.path.join(RESULTS, "IQ9075_vs_OrinAGX_vs_Thor_Colleague_Request.xlsx")
    for p in (SRC, md_path, xl_path):
        if not os.path.exists(p):
            sys.exit(f"FATAL: missing {p}")
    D = json.load(open(SRC))
    md = open(md_path, encoding="utf-8").read()
    xl = load_xlsx_text(xl_path)
    if xl is None:
        sys.exit("FATAL: openpyxl unavailable - cannot verify the workbook")

    fails, warns = [], []

    # ── C2: superseded values ────────────────────────────────────────────────
    superseded = {}
    for key, block in D.items():
        if not isinstance(block, dict):
            continue
        marks = [k for k in block if k.startswith("_SUPERSEDED")]
        if not marks:
            continue
        scoped = [m for m in marks if m.endswith("_ONLY")]
        for jp, v in walk(block):
            if any(jp.endswith(m) for m in marks):
                continue
            # scoped marker: only the named subtree is retired
            if scoped:
                tokens = {t for m in scoped for t in m.lower().replace("_only", "").split("_") if len(t) > 2}
                tokens.discard("superseded")
                if not any(t in jp.lower() for t in tokens):
                    continue
            if isinstance(v, float) and abs(v) > 1 and round(v, 4) != round(v, 0):
                superseded.setdefault(round(v, 4), f"{key}.{jp}")
    live = set()
    for key, block in D.items():
        if isinstance(block, dict) and any(k.startswith("_SUPERSEDED") for k in block):
            continue
        for _, v in walk({key: block}):
            if isinstance(v, float):
                live.add(round(v, 4))
    for v, origin in sorted(superseded.items()):
        if v in live:
            continue                       # also present in a current block: fine
        s = f"{v:g}"
        for name, text in (("md", md), ("xlsx", xl)):
            if re.search(rf"(?<![\d.\-\u2013\u2014]){re.escape(s)}(?![\d\-\u2013\u2014x×])", text):
                fails.append(f"C2 superseded value {s} ({origin}) appears in {name}")

    # ── C0: THE ARTIFACTS MUST BE NEWER THAN THEIR INPUTS ────────────────────
    # When the builder raises, it leaves the PREVIOUS artifacts on disk. Every check below
    # then validates the old files and reports clean, so a broken build reads as a passing
    # one. Hit exactly that way tonight: a KeyError aborted the build and the suite still
    # said "0 failures". A checker that cannot tell it is reading a stale artifact is
    # measuring the wrong file.
    import os as _os
    _src = SRC
    _bld = _os.path.join(BENCH, "build_colleague_xls.py")
    for _art in (md_path, xl_path):
        if not _os.path.exists(_art):
            fails.append(f"C0 {_os.path.basename(_art)} does not exist — the build did not run")
            continue
        _a = _os.path.getmtime(_art)
        for _dep, _lab in ((_src, "source of record"), (_bld, "builder")):
            if _os.path.exists(_dep) and _os.path.getmtime(_dep) > _a + 1:
                fails.append(
                    f"C0 {_os.path.basename(_art)} is STALE: the {_lab} is newer than it. The "
                    f"build did not complete, so every check below is reading the PREVIOUS "
                    f"artifact and a broken build would report clean.")

    # ── C1: md vs xlsx agreement ─────────────────────────────────────────────
    md_n, xl_n = numbers_in(md), numbers_in(xl)
    # isinstance(v, float) EXCLUDED EVERY INTEGER IN THE SOURCE. A source value of 450
    # could therefore never match a deliverable's 450, so C5 reported it as untraceable.
    # That is a large share of the 235 warnings, and warnings that are mostly false are
    # why nobody read them -- which is how the one real fabrication hid among them.
    src_n = {round(float(v), 4) for _, v in walk(D)
             if isinstance(v, (int, float)) and not isinstance(v, bool)}
    # A MAGNITUDE MUST MATCH ITS SIGNED SOURCE. The extractor reads "-19.6%" as 19.6 because
    # the minus is separate punctuation, while the source field holds -19.6. Without this a
    # correctly-sourced delta reports as untraceable, and the obvious "fix" is to hardcode
    # it -- turning a checker artifact into a real provenance loss.
    src_n |= {abs(v) for v in list(src_n)}
    # Numbers that appear in the source ONLY inside prose strings. These are not
    # fabrications -- they are worse in one specific way: they look sourced, and they are,
    # but they have no field, no unit, and no provenance tag, so nothing can check them and
    # they drift from the structured fields silently. 53.81 MB of fp16 VTCM spill existed
    # only inside the sentence at .IQ9_FP16_2026-08-17.mechanism. Same disease as a
    # calibration set named only in prose.
    src_prose_n = set()
    for _, v in walk(D):
        if isinstance(v, str):
            for m in re.finditer(r"(?<![\w.])(\d+(?:\.\d+)?)(?!\d|\.\d)", v):
                src_prose_n.add(round(float(m.group(1)), 4))
    def _present(n, pool):
        for scale in (1, 1000, 0.001, 4, 0.25):          # us<->ms, per-batch<->per-image
            v = n * scale
            if any(abs(v - q) <= max(0.0015, abs(v) * 0.002) for q in pool):
                return True
        return False
    # Compare EVERY number, not only those verbatim in the source. Filtering to
    # `n in src_n` meant rounded display values -- most of the document -- were never
    # compared: a headline 1429.64 shown as "1430" could be changed to "1043" in one
    # artifact with no complaint, because 1430 is not itself a source value.
    only_md = sorted(n for n in md_n - xl_n if not _present(n, xl_n))
    only_xl = sorted(n for n in xl_n - md_n if not _present(n, md_n))
    # C1 BLOCKS. It was warning-only, which meant the check the gate exists for could
    # not stop anything -- three retraction disclosures and the equal-precision
    # counter-numbers shipped in the workbook only, as warnings nobody reads.
    # DIRECTION MATTERS, and this check previously treated both the same. The defect that
    # motivated C1 was disclosures living in the WORKBOOK ONLY while the markdown -- the file
    # that actually gets forwarded -- shipped without them. That direction still BLOCKS.
    # The reverse is not the same hazard: the md is a prose document that legitimately
    # elaborates (derived multipliers, worked examples) on facts the workbook states as
    # tables. Failing on those forced a choice between deleting real explanation from the md
    # or padding the xlsx with sentences, neither of which serves the reader.
    # A md-only value is still REPORTED, so a genuine one-sided fix is visible -- it just
    # does not block. If the same quantity appears in both files with DIFFERENT values, that
    # is caught by the only_xl branch and by C5 against the source.
    for n in only_md:
        warns.append(f"C1 {n:g} is in the md but not the xlsx — check this is prose "
                     f"elaboration and not a fix that landed in one file only")
    for n in only_xl:
        fails.append(f"C1 {n:g} is in the xlsx but NOT the md (source value) — "
                     f"the md is the file that gets forwarded")

    # ── C5: numbers that exist in neither the source nor as a derived form ───
    for name, text in (("md", md), ("xlsx", xl)):
        for n in sorted(numbers_in(text)):
            if n in src_n:
                continue
            if any(abs(n - s / d) < 0.002 for s in src_n for d in (2, 3, 4, 8, 16)):
                continue                   # per-image / per-chunk derivations
            if any(abs(n - s * d) < 0.002 for s in src_n for d in (2, 3, 4)):
                continue
            # RECIPROCAL DERIVATIONS. IPS = 1000/ms is a declared, standard conversion used
            # throughout the batch tables, and C5 recognised only division and
            # multiplication -- so every IPS cell warned against the very latency it was
            # computed from. 21 of the warnings were this. Tolerance scales with the value
            # because a reciprocal magnifies rounding in the source.
            if any(s > 0 and abs(n - 1000.0 / s) <= max(0.05, abs(n) * 0.001) for s in src_n):
                continue
            if any(s > 0 and abs(n - 1.0 / s) <= max(0.0005, abs(n) * 0.001) for s in src_n):
                continue
            # ROUNDING MODE. This compared against Python's round(), which is round-half-
            # EVEN: round(2.1765, 3) -> 2.176. Builders and humans round half-UP, giving
            # 2.177. The check therefore flagged a correctly-rounded Thor batch-knee value
            # as untraceable -- and because that value is the bolded minimum in its row, it
            # was the one that places the knee. A false positive on a load-bearing cell is
            # expensive: it costs exactly the trust the checker exists to create.
            # Accept any rounding mode: n at d decimals matches s if |n-s| <= half a unit
            # in n's last displayed place.
            # n is a FLOAT, so str(n) always contains a "." -- str(1430.0) is "1430.0",
            # which counted 1 decimal and gave a 0.05 tolerance where 0.5 was correct.
            # Every integer-valued display therefore got a 10x too-tight window and warned
            # against its own source: 1430 vs the source's 1429.64 read as untraceable.
            # Strip trailing zeros first so the DISPLAYED precision drives the tolerance.
            _t = f"{n:.4f}".rstrip("0").rstrip(".")
            _d = len(_t.split(".")[-1]) if "." in _t else 0
            if any(abs(n - s) <= 0.5 * (10 ** -_d) + 1e-12 for s in src_n):
                continue                   # rounded for display, any rounding mode
            # C5 BLOCKS on measurement-shaped values. It was warning-only, which is the
            # exact defect the comment above C1 describes -- "the check the gate exists
            # for could ship as warnings nobody reads". C5's stated job is to catch
            # HARDCODING, and it reported 0 failures on a builder holding 49 typed
            # decimals that appear in the shipped workbook, including a sentence where a
            # record-sourced value and two literals sit side by side.
            #
            # A value with >=2 decimal places is a measurement, not configuration: batch
            # sizes, port numbers, years and core counts are integers. So decimals FAIL
            # and integers WARN -- precision instead of a blanket promotion, because a
            # check that fails 235 times is as unread as one that warns 235 times.
            if round(n, 4) != round(n, 1) or (n != int(n) and len(str(n).split('.')[-1]) >= 2):
                if round(n, 4) in src_prose_n:
                    fails.append(
                        f"C5 {name}: {n:g} exists in the source ONLY INSIDE PROSE, never as "
                        f"a field. It has no unit, no provenance tag and no structured home, "
                        f"so no check can verify it and it drifts from the numeric fields "
                        f"silently. Promote it to a field.  [M42]")
                else:
                    fails.append(
                        f"C5 {name}: {n:g} is measurement-shaped and traces to NO source "
                        f"value at all — a number that looks measured and comes from nowhere "
                        f"is a fabrication until it has a record  [M20]")
            else:
                warns.append(f"C5 {name}: {n:g} traces to no source value (hardcoded?)")

    # ── C3: "not measured" claims contradicted by the source ────────────────
    measured_blocks = " ".join(k for k in D if "FP16" in k.upper() or "MEASURE" in k.upper())
    for name, text in (("md", md), ("xlsx", xl)):
        for m in re.finditer(r"[^.\n]{0,120}(never measured|was not measured|only int8 was measured)[^.\n]{0,80}", text, re.I):
            frag = m.group(0).strip()
            if re.search(r"fp16|float", frag, re.I) and "IQ9_FP16_2026-08-17" in D:
                fails.append(f"C3 {name}: claims fp16 not measured, but IQ9_FP16 exists — \"{frag[:90]}\"")

    # ── C9: every narrative claim must appear in BOTH artifacts ─────────────
    # THE ROOT CAUSE, mechanised. All three audits converged on one finding: the
    # workbook read its claims from JSON while the markdown had them hardcoded, so a
    # correction landed in one file and missed the other. A claim now lives ONCE in
    # DELIVERABLE_NARRATIVE and this check makes it impossible to ship an artifact
    # that has dropped one.
    narr = D.get("DELIVERABLE_NARRATIVE")
    if narr is None:
        fails.append("C9: DELIVERABLE_NARRATIVE is missing from the source — the claim check "
                     "would silently pass. Renaming that block must not disable the gate.")
        narr = {}
    def _norm(t):
        return re.sub(r"[\s*_`]+", " ", t).strip().lower()
    for k, claim in narr.items():
        if k == "_contract":
            continue
        if k.startswith("_") and k != "_contract":
            fails.append(f"C9: narrative key '{k}' is underscore-prefixed, which retires it from "
                         f"BOTH artifacts silently. Retire a claim with an explicit _RETIRED_BY note.")
            continue
        if not isinstance(claim, str):
            fails.append(f"C9: narrative claim '{k}' is not a string ({type(claim).__name__}); "
                         f"non-str values are skipped and would vanish from both artifacts")
            continue
        for name, text in (("md", md), ("xlsx", xl)):
            if _norm(claim) not in _norm(text):
                fails.append(f"C9 {name}: missing narrative claim '{k}' — "
                             f"\"{claim[:70]}...\" (defined in DELIVERABLE_NARRATIVE)")

    # ── C7: a conclusion the SOURCE withdrew must not appear in an artifact ──
    # Both prior gates compared NUMBERS across artifacts and passed a document that
    # republished, in bold, a conclusion the source of record explicitly withdrew --
    # because the markdown's prose was hardcoded while the workbook read from JSON.
    # A withdrawal is a claim, not a value, so it needs its own check.
    for key, block in D.items():
        if not isinstance(block, dict):
            continue
        for jp, v in walk(block):
            if "WITHDRAWN" not in jp.upper() or not isinstance(v, str):
                continue
            # pull quoted phrases out of the withdrawal notice; those are the banned claims
            for phrase in re.findall(r"[\'\"\u2018\u2019\u201c\u201d]([^\'\"\u2018\u2019\u201c\u201d]{25,140})[\'\"\u2018\u2019\u201c\u201d]", v):
                norm = re.sub(r"\s+", " ", phrase).strip().lower()
                for name, text in (("md", md), ("xlsx", xl)):
                    if re.sub(r"[\s*_]+", " ", text).lower().find(norm) >= 0:
                        fails.append(f"C7 {name}: republishes a WITHDRAWN conclusion "
                                     f"(withdrawn at {key}.{jp}) — \"{phrase[:80]}\"")

    # ── C8: token-unit slippage ─────────────────────────────────────────────
    # Two harnesses in this corpus disagreed on whether "N tokens" meant input-prompt
    # tokens or runtime tokens (the chat template adds 10). That produced a 2x error
    # on the exact figure the recipient asked for. Any token count near a documented
    # chunk boundary must say which it is.
    if "IQ9_PREFILL_CHUNK_MODEL_2026-08-17" in D:
        for name, text in (("md", md), ("xlsx", xl)):
            for m in re.finditer(r"(\d{2,4})[- ]token", text):
                n = int(m.group(1))
                if n % 128 in (0, 1) or abs(n % 128 - 128) <= 1:
                    ctx = text[max(0, m.start()-160):m.end()+160].lower()
                    if not re.search(r"runtime|input[- ]prompt|template", ctx):
                        warns.append(f"C8 {name}: '{n}-token' sits on a chunk boundary "
                                     f"without saying runtime-vs-input-prompt")

    # ── C4: blacklist ────────────────────────────────────────────────────────
    for phrase, why in BLACKLIST:
        for name, text in (("md", md), ("xlsx", xl)):
            for m in re.finditer(re.escape(phrase), text, re.I):
                ctx = re.sub(r"\s+", " ", text[max(0, m.start() - 200):m.end() + 200])
                if any(a in ctx for a in BLACKLIST_ALLOW):
                    continue
                fails.append(f"C4 {name}: banned phrase \"{phrase}\" — {why}")
                break

    # ── C6: replicate counts ────────────────────────────────────────────────
    # The source path here was HARDCODED to the 2026-08-17 block, which holds 2 replicates.
    # When a later re-measure used 3, this check called a TRUE statement a violation -- the
    # checker encoding a specific past, which is the exact failure mode it exists to catch.
    # Take the MAXIMUM replicate evidence across all blocks that declare one.
    rep = D.get("REMEASURE_UNDER_ROE_2026-08-17", {}).get("thor_fp16", {}).get("latency_replicate", {})
    nrep = max((len(v) for v in rep.values() if isinstance(v, list)), default=0)
    for _blk in D.values():
        if isinstance(_blk, dict):
            _r = _blk.get("replicates")
            if isinstance(_r, dict) and isinstance(_r.get("n_per_config"), int):
                nrep = max(nrep, _r["n_per_config"])
    for name, text in (("md", md), ("xlsx", xl)):
        for m in re.finditer(r"median of (\d+|two|three|four) (timing )?passes", text, re.I):
            claimed = {"two": 2, "three": 3, "four": 4}.get(m.group(1).lower())
            claimed = claimed or int(m.group(1))
            if nrep and claimed > nrep:
                fails.append(f"C6 {name}: claims median of {claimed} passes; source holds {nrep}")

    # ---- C10: no unrendered template placeholder may reach a reader ---------
    # An adversarial review on 2026-08-18 found this cell in the SHIPPED workbook:
    #   "Orin's calibrated int8 is {OI['latency_ms_median']['yolov8l_b1']} ms at -7.3% mAP"
    # A continuation string had lost its f-prefix, so Python emitted the source
    # expression verbatim. Nine checks, and not one of them looked for the most
    # embarrassing possible defect: the code showing through. It is also self-
    # refuting -- the facing sheet promises the build "fails if a key is missing".
    _PLACEHOLDER = re.compile(r"\{[A-Za-z_][A-Za-z0-9_]*\s*[\[\('\"]|"     # {D['k'] / {f( / {d["
                              r"\{[a-z_][a-z0-9_]*\}|"                        # {bare_name}
                              r"\{\{|\}\}")                                 # stray doubled braces
    for name, text in (("md", md), ("xlsx", xl)):
        for m in _PLACEHOLDER.finditer(text):
            ctx = text[max(0, m.start() - 45):m.start() + 55].replace("\n", " ")
            fails.append(f"C10 {name}: UNRENDERED TEMPLATE PLACEHOLDER reaches the reader "
                         f"-- ...{ctx}... A lost f-prefix prints the source expression.")
            break

    print("=" * 72)
    print("DELIVERABLE CHECK — runs before the cut, not after")
    print("=" * 72)
    for f in fails:
        print(f"  FAIL  {f}")
    for w in warns[:25]:
        print(f"  warn  {w}")
    if len(warns) > 25:
        print(f"  warn  ... and {len(warns)-25} more")
    for _f in fails:
        _chk = _f.split()[0] if _f else "?"
        _log_event("gate_trip", tool="deliverable_check", check=_chk, detail=_f[:300],
                   severity="fail")
    _log_event("gate_pass" if not fails else "gate_trip", tool="deliverable_check",
               check="SUMMARY", n_fail=len(fails), n_warn=len(warns))
    print(f"\n{len(fails)} failure(s), {len(warns)} warning(s)")
    if fails:
        print("\nBUILD BLOCKED. These are defects that have already shipped once.")
    return 1 if fails else 0


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        sys.exit(self_test())
    sys.exit(main())
